ci: Revert "Add a build with `--prefer-oldest`"
This reverts commit e9c4051afc92a225f88e6afe3203e62cec80afdb.

See #141. Fails with

    Error: [Cabal-7107]
    Could not resolve dependencies:
    [__0] trying: asl-parser-0.1.0.0 (user goal)
    [__1] trying: text-0.1 (dependency of asl-parser)
    [__2] next goal: base (dependency of asl-parser)
    [__2] rejecting: base; 3.0.3.1, 3.0.3.2, 4.0.0.0, ...
    [__2] rejecting: base-4.17.2.1/installed-4.17.2.1 ...
    [__2] skipping: base; 4.17.2.1, 4.18.0.0, 4.18.1.0, ...
    [__2] fail (backjumping, conflict set: asl-parser, base, text)
    Backjump limit reached (currently 4000, change with --max-...